"""loan modification

Revision ID: 435c196d2880
Revises: 5adab423769c
Create Date: 2025-12-25 17:53:05.327726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435c196d2880'
down_revision: Union[str, Sequence[str], None] = '5adab423769c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('ticket', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'loans', ['ticket'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='unique')
    op.drop_column('loans', 'ticket')
    # ### end Alembic commands ###
