"""add approved_by to loan

Revision ID: 82adc77e6173
Revises: 74010da8e240
Create Date: 2025-12-26 18:44:16.577432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82adc77e6173'
down_revision: Union[str, Sequence[str], None] = '74010da8e240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('approved_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'loans', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'approved_by_id')
    # ### end Alembic commands ###
