# Utiliser Python 3.12 slim
FROM python:3.12-slim

# Installer build tools et dépendances de scikit-surprise
# RUN apk add --no-cache build-base gfortran git \
    # && apk add --no-cache linux-headers

# Dossier de travail dans le container
WORKDIR /app

# Copier uniquement les dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code
COPY . .

# Exposer le port FastAPI
EXPOSE 8000

# Lancer FastAPI en dev avec auto-reload
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
